import 'dotenv/config'
import express, { type NextFunction, type Request, type Response } from 'express'
import cors from 'cors'
import helmet from 'helmet'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import { PrismaClient } from '@prisma/client'
import { z } from 'zod'

const prisma = new PrismaClient()
const app = express()
const port = Number(process.env.PORT ?? 4000)
const jwtSecret = process.env.JWT_SECRET ?? 'development-secret-change-me'
type Role = 'CE' | 'CA' | 'FAC'
type Session = { userName: string; role: Role; institute?: string }
type AuthedRequest = Request & { session?: Session }
app.use(helmet())
app.use(cors({
  origin: '*',
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
}))
app.use(express.json({ limit: '1mb' }))

function auth(req: AuthedRequest, res: Response, next: NextFunction) { const headerToken = req.headers.authorization?.replace('Bearer ', ''); const queryToken = typeof req.query.token === 'string' ? req.query.token : ''; const token = headerToken || queryToken; if (!token) return res.status(401).json({ error: 'Authentication required' }); try { req.session = jwt.verify(token, jwtSecret) as Session; next() } catch { return res.status(401).json({ error: 'Invalid or expired session' }) } }
function allow(...roles: Role[]) { return (req: AuthedRequest, res: Response, next: NextFunction) => req.session && roles.includes(req.session.role) ? next() : res.status(403).json({ error: 'Insufficient permissions' }) }
function facultyScope(req: AuthedRequest) { if (req.session?.role === 'FAC') return { PAN: req.session.userName }; if (req.session?.role === 'CE') return {}; return { inst_short_name: req.session?.institute } }
function safe(row: Record<string, unknown>) { const copy = { ...row }; delete copy.password; return copy }

app.post('/api/auth/login', async (req, res) => { const parsed = z.object({ user_name: z.string().trim().min(1).max(10), role: z.enum(['CE', 'CA', 'FAC']), password: z.string().min(1) }).safeParse(req.body); if (!parsed.success) return res.status(400).json({ error: 'Enter the username, role, and password.' }); const user = await prisma.user.findUnique({ where: { user_name_role: { user_name: parsed.data.user_name.toUpperCase(), role: parsed.data.role } } }); if (!user || !(await bcrypt.compare(parsed.data.password, user.password))) return res.status(401).json({ error: 'Invalid username, role, or password.' }); const institute = user.role === 'CA' ? user.user_name : undefined; const session: Session = { userName: user.user_name, role: user.role as Role, institute }; return res.json({ token: jwt.sign(session, jwtSecret, { expiresIn: '8h' }), user: { user_name: user.user_name, role: user.role, institute } }) })
app.get('/api/auth/me', auth, (req: AuthedRequest, res) => res.json({ user: req.session }))
app.post('/api/auth/logout', auth, (_req, res) => res.status(204).send())

app.get('/api/faculty', auth, async (req: AuthedRequest, res) => { const rows = await prisma.faculty.findMany({ where: facultyScope(req), orderBy: { faculty_name: 'asc' } }); return res.json(rows) })
app.get('/api/faculty/:PAN', auth, async (req: AuthedRequest, res) => { const row = await prisma.faculty.findUnique({ where: { PAN: String(req.params.PAN) } }); if (!row || (req.session?.role === 'FAC' ? row.PAN !== req.session.userName : req.session?.role === 'CA' && row.inst_short_name !== req.session.institute)) return res.status(404).json({ error: 'Faculty record not found' }); return res.json(row) })
app.post('/api/faculty', auth, allow('CE', 'CA', 'FAC'), async (req: AuthedRequest, res) => { const parsed = z.object({ PAN: z.string().trim().min(1).max(10), Title: z.string().max(10).optional(), faculty_name: z.string().max(50).optional(), inst_short_name: z.string().max(10).optional(), faculty_desig: z.string().max(25).optional(), faculty_total_exp: z.coerce.number().int().optional(), faculty_address: z.string().max(100).optional(), faculty_Email: z.string().email().max(50).optional(), faculty_MobileNo: z.string().max(10).optional() }).parse(req.body); if (req.session?.role === 'FAC' && parsed.PAN !== req.session.userName) return res.status(403).json({ error: 'Faculty can only create their own record' }); if (req.session?.role === 'CA' && parsed.inst_short_name && parsed.inst_short_name !== req.session.institute) return res.status(403).json({ error: 'Faculty must belong to your institute' }); const existing = await prisma.faculty.findUnique({ where: { PAN: parsed.PAN } }); if (existing) return res.status(409).json({ error: 'A faculty record with this PAN already exists' }); const data = { ...parsed, inst_short_name: req.session?.role === 'CA' ? req.session.institute : parsed.inst_short_name, entered_by: req.session?.userName, entered_on: new Date() }; return res.status(201).json(await prisma.faculty.create({ data })) })
app.put('/api/faculty/:PAN', auth, allow('CE', 'CA', 'FAC'), async (req: AuthedRequest, res) => { const existing = await prisma.faculty.findUnique({ where: { PAN: String(req.params.PAN) } }); if (!existing || (req.session?.role === 'FAC' && existing.PAN !== req.session.userName) || (req.session?.role === 'CA' && existing.inst_short_name !== req.session.institute)) return res.status(404).json({ error: 'Faculty record not found' }); const allowed = ['Title', 'faculty_name', 'inst_short_name', 'faculty_desig', 'faculty_total_exp', 'faculty_address', 'faculty_Email', 'faculty_MobileNo']; const data = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); if (req.session?.role === 'FAC') delete data.inst_short_name; return res.json(await prisma.faculty.update({ where: { PAN: String(req.params.PAN) }, data: { ...data, entered_by: req.session?.userName, entered_on: new Date() } })) })

app.get('/api/users', auth, allow('CE'), async (_req, res) => res.json((await prisma.user.findMany()).map(safe)))
app.post('/api/users', auth, allow('CE', 'CA'), async (req: AuthedRequest, res) => { const parsed = z.object({ user_name: z.string().min(1).max(10), password: z.string().min(8), role: z.enum(['CA', 'FAC']) }).parse(req.body); if (req.session?.role === 'CA' && parsed.role !== 'FAC') return res.status(403).json({ error: 'College Admin can only create Faculty credentials' }); if (req.session?.role === 'CA') { const faculty = await prisma.faculty.findUnique({ where: { PAN: parsed.user_name } }); if (!faculty || faculty.inst_short_name !== req.session.institute) return res.status(403).json({ error: 'Faculty must belong to your institute' }) } const row = await prisma.user.create({ data: { user_name: parsed.user_name, role: parsed.role, password: await bcrypt.hash(parsed.password, 12) } }); return res.status(201).json(safe(row)) })

const mappingModels: Record<string, 'instCourse' | 'courseSubject' | 'facultySubject' | 'facultySpec'> = { 'institute-courses': 'instCourse', 'course-subjects': 'courseSubject', 'faculty-subjects': 'facultySubject', 'faculty-specializations': 'facultySpec' }
app.get('/api/mappings/:type', auth, async (req: AuthedRequest, res) => { const model = mappingModels[String(req.params.type)]; if (!model) return res.status(404).json({ error: 'Unknown mapping type' }); const rows = await (prisma as any)[model].findMany(); if (req.session?.role === 'FAC') return res.json(rows.filter((row: any) => row.PAN === req.session?.userName)); if (req.session?.role === 'CA' && model.startsWith('faculty')) return res.json(rows.filter((row: any) => row.PAN && false)); return res.json(rows) })
app.post('/api/mappings/:type', auth, allow('CE', 'CA', 'FAC'), async (req: AuthedRequest, res) => { const model = mappingModels[String(req.params.type)]; if (!model) return res.status(404).json({ error: 'Unknown mapping type' }); if (req.session?.role === 'FAC' && !['faculty-subjects', 'faculty-specializations'].includes(String(req.params.type))) return res.status(403).json({ error: 'Faculty cannot manage this mapping' }); if (req.session?.role === 'FAC' && req.body.PAN !== req.session.userName) return res.status(403).json({ error: 'Faculty can only manage their own mappings' }); const data = { ...req.body, entered_by: req.session?.userName, entered_on: new Date() }; return res.status(201).json(await (prisma as any)[model].create({ data })) })
// INSTITUTE ENDPOINTS
app.get('/api/institutes', auth, allow('CE', 'CA'), async (req: AuthedRequest, res) => { const rows = req.session?.role === 'CA' ? await prisma.institute.findMany({ where: { inst_short_name: req.session.institute } }) : await prisma.institute.findMany(); return res.json(rows) })
app.get('/api/institutes/:inst_short_name', auth, allow('CE', 'CA'), async (req: AuthedRequest, res) => { const row = await prisma.institute.findUnique({ where: { inst_short_name: String(req.params.inst_short_name) } }); if (!row || (req.session?.role === 'CA' && row.inst_short_name !== req.session.institute)) return res.status(404).json({ error: 'Institute not found' }); return res.json(row) })
app.post('/api/institutes', auth, allow('CE'), async (req: AuthedRequest, res) => { const parsed = z.object({ inst_short_name: z.string().trim().min(1).max(10), inst_full_name: z.string().max(100).optional(), inst_Address1: z.string().max(100).optional(), inst_Address2: z.string().max(100).optional(), inst_District: z.string().max(50).optional(), inst_State: z.string().max(50).optional(), Landline_PhoneNo: z.string().max(20).optional(), Director_Name: z.string().max(50).optional(), Director_Desig: z.string().max(25).optional(), Director_Email: z.string().email().max(50).optional(), Director_MobileNo: z.string().max(10).optional(), ExamHead_Name: z.string().max(50).optional(), ExamHead_Desig: z.string().max(25).optional(), ExamHead_Email: z.string().email().max(50).optional(), ExamHead_MobileNo: z.string().max(10).optional() }).parse(req.body); const existing = await prisma.institute.findUnique({ where: { inst_short_name: parsed.inst_short_name } }); if (existing) return res.status(409).json({ error: 'Institute already exists' }); return res.status(201).json(await prisma.institute.create({ data: parsed })) })
app.put('/api/institutes/:inst_short_name', auth, allow('CE', 'CA'), async (req: AuthedRequest, res) => { const instShortName = String(req.params.inst_short_name); if (req.session?.role === 'CA' && instShortName !== req.session.institute) return res.status(403).json({ error: 'You can only edit your own institute' }); const existing = await prisma.institute.findUnique({ where: { inst_short_name: instShortName } }); if (!existing) return res.status(404).json({ error: 'Institute not found' }); const allowed = ['inst_full_name', 'inst_Address1', 'inst_Address2', 'inst_District', 'inst_State', 'Landline_PhoneNo', 'Director_Name', 'Director_Desig', 'Director_Email', 'Director_MobileNo', 'ExamHead_Name', 'ExamHead_Desig', 'ExamHead_Email', 'ExamHead_MobileNo']; const data = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); return res.json(await prisma.institute.update({ where: { inst_short_name: instShortName }, data })) })

// COURSE ENDPOINTS
app.get('/api/courses', auth, async (_req, res) => res.json(await prisma.course.findMany({ orderBy: { course_code: 'asc' } })))
app.get('/api/courses/:course_code', auth, async (req: AuthedRequest, res) => { const row = await prisma.course.findUnique({ where: { course_code: String(req.params.course_code) } }); if (!row) return res.status(404).json({ error: 'Course not found' }); return res.json(row) })
app.post('/api/courses', auth, allow('CE'), async (req: AuthedRequest, res) => { const parsed = z.object({ course_code: z.string().trim().min(1).max(3), course_short_name: z.string().max(10).optional(), course_full_name: z.string().max(100).optional() }).parse(req.body); const existing = await prisma.course.findUnique({ where: { course_code: parsed.course_code } }); if (existing) return res.status(409).json({ error: 'Course already exists' }); return res.status(201).json(await prisma.course.create({ data: parsed })) })
app.put('/api/courses/:course_code', auth, allow('CE'), async (req: AuthedRequest, res) => { const courseCode = String(req.params.course_code); const existing = await prisma.course.findUnique({ where: { course_code: courseCode } }); if (!existing) return res.status(404).json({ error: 'Course not found' }); const allowed = ['course_short_name', 'course_full_name']; const data = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); return res.json(await prisma.course.update({ where: { course_code: courseCode }, data })) })
app.delete('/api/courses/:course_code', auth, allow('CE'), async (req: AuthedRequest, res) => { try { await prisma.course.delete({ where: { course_code: String(req.params.course_code) } }); return res.status(204).send() } catch { return res.status(400).json({ error: 'Cannot delete course with existing mappings' }) } })

// SPECIALIZATION ENDPOINTS
app.get('/api/specializations', auth, async (_req, res) => res.json(await prisma.specialization.findMany({ orderBy: { spec_id: 'asc' } })))
app.get('/api/specializations/:spec_id', auth, async (req: AuthedRequest, res) => { const specId = Number(Array.isArray(req.params.spec_id) ? req.params.spec_id[0] : req.params.spec_id); const row = await prisma.specialization.findUnique({ where: { spec_id: specId } }); if (!row) return res.status(404).json({ error: 'Specialization not found' }); return res.json(row) })
app.post('/api/specializations', auth, allow('CE'), async (req: AuthedRequest, res) => { const parsed = z.object({ spec_id: z.number().int().min(1), spec_name: z.string().max(30).optional() }).parse(req.body); const existing = await prisma.specialization.findUnique({ where: { spec_id: parsed.spec_id } }); if (existing) return res.status(409).json({ error: 'Specialization already exists' }); return res.status(201).json(await prisma.specialization.create({ data: parsed })) })
app.put('/api/specializations/:spec_id', auth, allow('CE'), async (req: AuthedRequest, res) => { const specId = Number(Array.isArray(req.params.spec_id) ? req.params.spec_id[0] : req.params.spec_id); const existing = await prisma.specialization.findUnique({ where: { spec_id: specId } }); if (!existing) return res.status(404).json({ error: 'Specialization not found' }); const allowed = ['spec_name']; const data = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); return res.json(await prisma.specialization.update({ where: { spec_id: specId }, data })) })
app.delete('/api/specializations/:spec_id', auth, allow('CE'), async (req: AuthedRequest, res) => { try { const specId = Number(Array.isArray(req.params.spec_id) ? req.params.spec_id[0] : req.params.spec_id); await prisma.specialization.delete({ where: { spec_id: specId } }); return res.status(204).send() } catch { return res.status(400).json({ error: 'Cannot delete specialization with existing mappings' }) } })

// SUBJECT ENDPOINTS
app.get('/api/subjects', auth, async (_req, res) => res.json(await prisma.subject.findMany({ orderBy: { subject_code: 'asc' } })))
app.get('/api/subjects/:subject_code', auth, async (req: AuthedRequest, res) => { const row = await prisma.subject.findUnique({ where: { subject_code: String(req.params.subject_code) } }); if (!row) return res.status(404).json({ error: 'Subject not found' }); return res.json(row) })
app.post('/api/subjects', auth, allow('CE'), async (req: AuthedRequest, res) => { const parsed = z.object({ subject_code: z.string().trim().min(1).max(10), sub_subject_codes: z.string().max(100).optional(), subject_short_name: z.string().max(10).optional(), subject_full_name: z.string().max(100).optional(), semester: z.number().int().optional(), spec_id: z.number().int().optional() }).parse(req.body); const existing = await prisma.subject.findUnique({ where: { subject_code: parsed.subject_code } }); if (existing) return res.status(409).json({ error: 'Subject already exists' }); return res.status(201).json(await prisma.subject.create({ data: parsed })) })
app.put('/api/subjects/:subject_code', auth, allow('CE'), async (req: AuthedRequest, res) => { const subjectCode = String(req.params.subject_code); const existing = await prisma.subject.findUnique({ where: { subject_code: subjectCode } }); if (!existing) return res.status(404).json({ error: 'Subject not found' }); const allowed = ['sub_subject_codes', 'subject_short_name', 'subject_full_name', 'semester', 'spec_id']; const data = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); return res.json(await prisma.subject.update({ where: { subject_code: subjectCode }, data })) })
app.delete('/api/subjects/:subject_code', auth, allow('CE'), async (req: AuthedRequest, res) => { try { await prisma.subject.delete({ where: { subject_code: String(req.params.subject_code) } }); return res.status(204).send() } catch { return res.status(400).json({ error: 'Cannot delete subject with existing mappings' }) } })

// INST_COURSE MAPPING ENDPOINTS
app.get('/api/inst-courses', auth, async (req: AuthedRequest, res) => { const rows = req.session?.role === 'CA' ? await prisma.instCourse.findMany({ where: { inst_short_name: req.session.institute } }) : await prisma.instCourse.findMany(); return res.json(rows) })
app.post('/api/inst-courses', auth, allow('CE', 'CA'), async (req: AuthedRequest, res) => { const parsed = z.object({ inst_short_name: z.string().max(10), course_code: z.string().max(3), intake: z.number().int().optional(), strength: z.number().int().optional() }).parse(req.body); if (req.session?.role === 'CA' && parsed.inst_short_name !== req.session.institute) return res.status(403).json({ error: 'You can only add courses to your institute' }); const data = { inst_short_name: parsed.inst_short_name, course_code: parsed.course_code, intake: parsed.intake, strength: parsed.strength }; return res.status(201).json(await prisma.instCourse.create({ data })) })
app.put('/api/inst-courses/:inst_short_name/:course_code', auth, allow('CE', 'CA'), async (req: AuthedRequest, res) => { const inst = String(req.params.inst_short_name); const course = String(req.params.course_code); if (req.session?.role === 'CA' && inst !== req.session.institute) return res.status(403).json({ error: 'You can only edit your institute courses' }); const allowed = ['intake', 'strength']; const data = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); return res.json(await prisma.instCourse.update({ where: { inst_short_name_course_code: { inst_short_name: inst, course_code: course } }, data })) })
app.delete('/api/inst-courses/:inst_short_name/:course_code', auth, allow('CE', 'CA'), async (req: AuthedRequest, res) => { const inst = String(req.params.inst_short_name); const course = String(req.params.course_code); if (req.session?.role === 'CA' && inst !== req.session.institute) return res.status(403).json({ error: 'You can only delete your institute courses' }); try { await prisma.instCourse.delete({ where: { inst_short_name_course_code: { inst_short_name: inst, course_code: course } } }); return res.status(204).send() } catch { return res.status(400).json({ error: 'Cannot delete mapping' }) } })

// COURSE_SUBJECT MAPPING ENDPOINTS
app.get('/api/course-subjects', auth, async (_req, res) => res.json(await prisma.courseSubject.findMany()))
app.post('/api/course-subjects', auth, allow('CE'), async (req: AuthedRequest, res) => { const parsed = z.object({ course_code: z.string().max(3), subject_code: z.string().max(10) }).parse(req.body); const data = { course_code: parsed.course_code, subject_code: parsed.subject_code }; return res.status(201).json(await prisma.courseSubject.create({ data })) })
app.delete('/api/course-subjects/:course_code/:subject_code', auth, allow('CE'), async (req: AuthedRequest, res) => { try { await prisma.courseSubject.delete({ where: { course_code_subject_code: { course_code: String(req.params.course_code), subject_code: String(req.params.subject_code) } } }); return res.status(204).send() } catch { return res.status(400).json({ error: 'Cannot delete mapping' }) } })

app.get('/api/faculty-export', auth, allow('CE', 'CA'), async (req: AuthedRequest, res) => { const rows = await prisma.faculty.findMany({ where: facultyScope(req) }); const columns = ['PAN', 'Title', 'faculty_name', 'inst_short_name', 'faculty_desig', 'faculty_total_exp', 'faculty_address', 'faculty_Email', 'faculty_MobileNo']; const csv = [columns.join(','), ...rows.map((row: any) => columns.map((column) => JSON.stringify(row[column] ?? '')).join(','))].join('\n'); res.setHeader('Content-Type', 'text/csv'); res.setHeader('Content-Disposition', 'attachment; filename="faculty-export.csv"'); return res.send(csv) })
app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { console.error('[v0] API error', error); return res.status(400).json({ error: error instanceof Error ? error.message : 'Unexpected server error' }) })
app.listen(port, () => console.log(`[v0] Examiner API listening on ${port}`))
